### ISSUE TITLE
Cannot Delete Player From Group

### ISSUE THREAD

**Issue by malmby** [NemeStats/NemeStats#512] opened 2016-10-05 19:02 UTC
Player ID: 20168
Group ID: 13749

All plays with player involved deleted -- still a "game champion"; attempting to delete the player throws an "oh crap!" error. Able to delete other players with no plays ever logged.

**Comment by jakejgordon** [comment] 2016-10-05 21:58
Thanks for posting. This is a duplicate of #501 so I'll close.

**Closed by jakejgordon** 2016-10-05 21:58 UTC
